# Generated by Django 2.1.7 on 2019-04-01 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorDetailJson',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_update', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('last_operation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间')),
                ('lat', models.TextField(null=True)),
                ('lon', models.TextField(null=True)),
                ('beds', models.TextField(null=True)),
                ('sqft', models.TextField(null=True)),
                ('baths', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('lot_size', models.TextField(null=True)),
                ('data_interface', models.TextField(null=True)),
                ('is_dirty', models.TextField(null=True)),
                ('detail_json', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tb_realtor_detail_json',
            },
        ),
        migrations.CreateModel(
            name='RealtorListPageJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(null=True)),
                ('last_operation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间')),
            ],
            options={
                'db_table': 'tb_realtor_list_page_json',
            },
        ),
        migrations.CreateModel(
            name='RealtorListPageJsonSplite',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_update', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('last_operation_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间')),
                ('lat', models.TextField(null=True)),
                ('lon', models.TextField(null=True)),
                ('beds', models.TextField(null=True)),
                ('sqft', models.TextField(null=True)),
                ('baths', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('lot_size', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tb_realtor_list_page_json_splite',
            },
        ),
    ]
