# Generated by Django 2.1.7 on 2019-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtordetailjson',
            name='last_update',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='last_update',
            field=models.TextField(),
        ),
    ]
