# Generated by Django 2.1.7 on 2019-03-24 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider_server', '0002_auto_20190324_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtordetailjson',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='baths',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='beds',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='data_interface',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='detail_json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='is_dirty',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='last_operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='last_update',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='lat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='lon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='lot_size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtordetailjson',
            name='sqft',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejson',
            name='json_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejson',
            name='last_operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='baths',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='beds',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='last_operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='last_update',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='lat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='lon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='lot_size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realtorlistpagejsonsplite',
            name='sqft',
            field=models.TextField(null=True),
        ),
    ]
